# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

env:
 global:
 - SIG_USER=commercial
 - secure: "HGTGThYIkhnrXPPAkPLsYQjSC1z3Z3vp71n1U04yBPHlzfn3Tp/xv0wPAayy4EPj6XrjQuEGjYRKoKHflOVNWWbv+CrAEWL2pghssiBoDgox13Pwg+L4C59/B3cz+eLAyQ0Zu0IOub7lOGhZ7esTVwEPpPFCzlUWATuPn+kzn5A="

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- (cd src/soh-upload && stack $ARGS --no-terminal --install-ghc test --pedantic --haddock --copy-bins)

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
- if [ $TRAVIS_BRANCH = 'master' -a $TRAVIS_PULL_REQUEST = 'false' ]; then ./src/soh-upload/upload.sh; fi

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
